name: MODFLOW 6 full distribution test
on:
  schedule:
    - cron: '0 13 * * *' # run at 2 AM UTC
  push:
    branches:
      - master
      - develop
      - ci-diagnose*
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
  # workflow_dispatch trigger to start release via GitHub UI or CLI,
  # see https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
  workflow_dispatch:
jobs:
  get_version:
    name: Get current version
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash -l {0}
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:

      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          repository: MODFLOW-ORG/modflow6-nightly-build

      - name: Checkout modflow6
        uses: actions/checkout@v5
        with:
          repository: MODFLOW-ORG/modflow6
          path: modflow6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Install Python packages
        run: pip install -r requirements.txt
      
      - name: Get version
        working-directory: modflow6/distribution
        id: get_version
        run: |
          ver=$(python update_version.py -g)
          echo "version=${ver}" >> "$GITHUB_OUTPUT"

  make_dist:
    name: Make releasemode distribution
    needs: get_version
    uses: wpbonelli/modflow6/.github/workflows/release.yml@release-scripts
    with:
      branch: release-scripts
      releasemode: true
      run_tests: true
      version: "${{ needs.get_version.outputs.version }}"